In [50]:
import array as arr
import numpy as np
# E:\P2\OP2

In [51]:
from numpy import asarray
from numpy import savetxt

In [52]:
from numpy import genfromtxt
CO_arr_jan = genfromtxt('C:/Users/Desktop/J Prgrm/CO new OUTPUT/CO_jan.csv', delimiter=',')
CO_arr_feb = genfromtxt('C:/Users/Desktop/J Prgrm/CO new OUTPUT/CO_feb.csv', delimiter=',')
CO_arr_mar = genfromtxt('C:/Users/Desktop/J Prgrm/CO new OUTPUT/CO_march.csv', delimiter=',')
CO_arr_apr = genfromtxt('C:/Users/Desktop/J Prgrm/CO new OUTPUT/CO_april.csv', delimiter=',')
CO_arr_may = genfromtxt('C:/Users/Desktop/J Prgrm/CO new OUTPUT/CO_may.csv', delimiter=',')
CO_arr_jun = genfromtxt('C:/Users/Desktop/J Prgrm/CO new OUTPUT/CO_june.csv', delimiter=',')
CO_arr_jul = genfromtxt('C:/Users/Desktop/J Prgrm/CO new OUTPUT/CO_july.csv', delimiter=',')
CO_arr_aug = genfromtxt('C:/Users/Desktop/J Prgrm/CO new OUTPUT/CO_aug.csv', delimiter=',')
CO_arr_sep = genfromtxt('C:/Users/Desktop/J Prgrm/CO new OUTPUT/CO_sept.csv', delimiter=',')
CO_arr_oct = genfromtxt('C:/Users/Desktop/J Prgrm/CO new OUTPUT/CO_oct.csv', delimiter=',')
CO_arr_nov = genfromtxt('C:/Users/Desktop/J Prgrm/CO new OUTPUT/CO_nov.csv', delimiter=',')
CO_arr_dec = genfromtxt('C:/Users/Desktop/J Prgrm/CO new OUTPUT/CO_Dec.csv', delimiter=',')
COlist=[CO_arr_jan,CO_arr_feb,CO_arr_mar,CO_arr_apr,CO_arr_may,CO_arr_jun,CO_arr_jul,CO_arr_aug,CO_arr_sep,CO_arr_oct,CO_arr_nov,CO_arr_dec]


In [53]:
df=['','','','','','','','','','','','']

In [54]:
i=0
for x in COlist:
    arr=np.array(x)
    arr_list= arr.flatten()
    df[i]=arr_list
    i=i+1
df
# arr
# arr_list= arr.flatten()
# print(arr_list)

[array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.])]

In [55]:
dft= np.transpose(df)

In [56]:
savetxt('E:/GIS_IIRS/P2/Output/test_dft.csv',dft, delimiter=',')

In [57]:
savetxt('E:/GIS_IIRS/P2/Output/test_56.csv',df, delimiter=',')

In [58]:
arr_jan = genfromtxt('C:/Users/Desktop/J Prgrm/LST_OUTPUT_new/lst_output_jan.csv', delimiter=',')
arr_feb = genfromtxt('C:/Users/Desktop/J Prgrm/LST_OUTPUT_new/lst_output_feb.csv', delimiter=',')
arr_mar = genfromtxt('C:/Users/Desktop/J Prgrm/LST_OUTPUT_new/lst_output_mar.csv', delimiter=',')
arr_apr = genfromtxt('C:/Users/Desktop/J Prgrm/LST_OUTPUT_new/lst_output_apr.csv', delimiter=',')
arr_may = genfromtxt('C:/Users/Desktop/J Prgrm/LST_OUTPUT_new/lst_output_may.csv', delimiter=',')
arr_jun = genfromtxt('C:/Users/Desktop/J Prgrm/LST_OUTPUT_new/LST_jun.csv', delimiter=',')
arr_jul = genfromtxt('C:/Users/Desktop/J Prgrm/LST_OUTPUT_new/LST_july.csv', delimiter=',')
arr_aug = genfromtxt('C:/Users/Desktop/J Prgrm/LST_OUTPUT_new/LST_aug.csv', delimiter=',')
arr_sep = genfromtxt('C:/Users/Desktop/J Prgrm/LST_OUTPUT_new/LST_sept.csv', delimiter=',')
arr_oct = genfromtxt('C:/Users/Desktop/J Prgrm/LST_OUTPUT_new/lst_output_oct.csv', delimiter=',')
arr_nov = genfromtxt('C:/Users/Desktop/J Prgrm/LST_OUTPUT_new/LST_nov.csv', delimiter=',')
arr_dec = genfromtxt('C:/Users/Desktop/J Prgrm/LST_OUTPUT_new/LST_dec.csv', delimiter=',')
lstlist=[arr_jan,arr_feb,arr_mar,arr_apr,arr_may,arr_jun,arr_jul,arr_aug,arr_sep,arr_oct,arr_nov,arr_dec]

In [59]:
df2=['','','','','','','','','','','','']
# df = pd.read_csv('E:/GIS_IIRS/P2/Output/test_55.csv')

In [60]:
i=0
for x in lstlist:
    arr=np.array(x)
    arr_list= arr.flatten()
    df2[i]=arr_list
    i=i+1

In [66]:
i=0
for x in lstlist and COlist:
    arr1=np.array(lstlist[i])
    LST_arr= arr1.flatten()
    arr2=np.array(COlist[i])
    CO_arr= arr2.flatten()
    d=np.corrcoef(CO_arr,LST_arr)
    print(d)
    i=i+1

[[1.         0.99897089]
 [0.99897089 1.        ]]
[[1.         0.87067788]
 [0.87067788 1.        ]]
[[1.         0.98320811]
 [0.98320811 1.        ]]
[[1.         0.99564213]
 [0.99564213 1.        ]]
[[1.         0.99571529]
 [0.99571529 1.        ]]
[[1.         0.98605553]
 [0.98605553 1.        ]]
[[1.         0.98718092]
 [0.98718092 1.        ]]
[[1.         0.79165121]
 [0.79165121 1.        ]]
[[1.         0.82035505]
 [0.82035505 1.        ]]
[[1.         0.99723237]
 [0.99723237 1.        ]]
[[1.         0.99308777]
 [0.99308777 1.        ]]
[[1.         0.99792829]
 [0.99792829 1.        ]]


In [24]:
df2t= np.transpose(df2)

In [25]:
savetxt('E:/GIS_IIRS/P2/Output/test_df2t.csv',df2t, delimiter=',')

In [70]:
df_new= dft.flatten()
df2_new= df2t.flatten()

In [74]:
savetxt('E:/GIS_IIRS/P2/Output/test_df_new.csv',df_new, delimiter=',')
savetxt('E:/GIS_IIRS/P2/Output/test_df2_new.csv',df2_new, delimiter=',')

In [72]:
d=np.corrcoef(df_new,df2_new)

In [75]:
savetxt('E:/GIS_IIRS/P2/Output/Overall_Corelation.csv',d, delimiter=',')

In [37]:
savetxt('E:/GIS_IIRS/P2/Output/test_df_newer.csv',df_newer, delimiter=',')
savetxt('E:/GIS_IIRS/P2/Output/test_df2_newer.csv',df2_newer, delimiter=',')